# Déploiement Spring Boot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: springboot-app:latest
          imagePullPolicy: Never   # utiliser image locale Minikube
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: api-key

---
# Service Spring Boot
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort