# Stockage persistant pour PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: pgdb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Déploiement PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgdb
  labels:
    app: pgdb
    tier: database
spec:
  selector:
    matchLabels:
      app: pgdb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgdb
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: pgdb
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
# Service PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: pgdb
  labels:
    app: pgdb
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: pgdb
    tier: database
  clusterIP: None